### ISSUE TITLE
Updating swap value doesn't work?

### ISSUE THREAD

**Issue by shinebayar-g** [geerlingguy/ansible-role-swap#31]
```yml
  roles:
    - role: geerlingguy.swap
      become: true
      vars:
        swap_file_size_mb: '1024'
```

Previously I had this setup. After changing 1024 to 512, it does nothing.
