### ISSUE TITLE
Builds failing after fix for #32

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-swap#33]
Ah so fun... #32 fix from #26 fix means CI is failing with:

```
  TASK [geerlingguy.swap : include_tasks] ****************************************
  fatal: [instance]: FAILED! => {"msg": "The conditional check 'swap_file_state == 'absent' or (swap_file_state == 'present' and swap_file_existing_size_mb != swap_file_size_mb)' failed. The error was: error while evaluating conditional (swap_file_state == 'absent' or (swap_file_state == 'present' and swap_file_existing_size_mb != swap_file_size_mb)): 'swap_file_existing_size_mb' is undefined. 'swap_file_existing_size_mb' is undefined\n\nThe error appears to be in '/home/runner/work/ansible-role-swap/ansible-role-swap/geerlingguy.swap/tasks/main.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_tasks: disable.yml\n  ^ here\n"}
```

**Comment by whysthatso** [comment]
hm, maybe i'm missing something, but i've added:

```
- name: Set variable if no swap file exists
  set_fact:
    swap_file_existing_size_mb: 0
  when: not swap_file_check.stat.exists
```
  after the first setter and that worked for me. should i make a pr for that?
