### ISSUE TITLE
Would like to be able to set mount options

### ISSUE THREAD

**Issue by iay** [geerlingguy/ansible-role-swap#40]
The mount line in `/etc/fstab` is hard-wired to have options set to "sw". It would be nice to be able to override this default, for example to set a `discard` policy.

Let me know if you'd be interested in a PR for this one.

**Comment by colin-nolan** [comment]
I also thought the same thing - https://github.com/geerlingguy/ansible-role-swap/pull/12. I ended up using a fork.

**Comment by khawarizmus** [comment]
@colin-nolan was it your fork? is this role no longer maintained?

**Comment by colin-nolan** [comment]
> was it your fork?

Yes - here's what I'm currently using in my Galaxy requirements yml:
```yml
  # Forked from upstream with PRs that will never be merged:
  #   - https://github.com/geerlingguy/ansible-role-swap/pull/11
  #   - https://github.com/geerlingguy/ansible-role-swap/pull/12
  - name: geerlingguy.swap
    src: https://github.com/colin-nolan/ansible-role-swap.git
    version: 82f2466905b3d01fe9ab825534370c4730fa9590
```

> is this role no longer maintained?

I can't comment on this role's maintainence status but I can direct you towards this (admittedly, rather old) post by Jeff: https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes.
> I see a lot of PRs for one-off functionality that I've personally never seen in the wild. Sure there are unicorn systems out there that need to configure hairy details in some obscure app... but I'm not going to include code for that in my projects because (a) I don't use it, so I can't vouch for it, and (b) it adds maintenance overhead—even if it's a 'simple' addition. If you are one of the unicorns, please fork my work. I won't get offended!
